### PR TITLE
Adds Bazel Build Support

### PR DESCRIPTION
**Pull request by tinder-maxwellelliott**
Adds support for the Bazel build system

### CODE REVIEW

**Comment by stephencelis** [comment]
Thanks for taking the time to open a pull request. Can you provide a bit more context as to what you'd like us to merge? We're not quite sure what Bazel CI adds here 😅

**Comment by tinder-maxwellelliott** [comment]
> Thanks for taking the time to open a pull request. Can you provide a bit more context as to what you'd like us to merge? We're not quite sure what Bazel CI adds here 😅

We do not use SPM, we use Bazel as our Build system. This allows anyone who uses Bazel to build this package

**Comment by stephencelis** [comment]
@tinder-maxwellelliott I see. We're not super familiar with Bazel. It seems like a nice thing to support, but don't think we'll be able to properly maintain it here. Is it possible to support it in an external repo somehow?

**Comment by tinder-maxwellelliott** [comment]
> @tinder-maxwellelliott I see. We're not super familiar with Bazel. It seems like a nice thing to support, but don't think we'll be able to properly maintain it here. Is it possible to support it in an external repo somehow?

What maintenance costs are you expecting? FWIW, other repos have had no issues adopting this system https://github.com/jpsim/Yams

In the spirit of Open Source I was hoping to be the last to need to implement this for others who use Bazel. We can keep this private in our repository, but that is no help to the next developer looking to use this package.

**Comment by mbrandonw** [comment]
@tinder-maxwellelliott Sorry for the delayed response but Stephen and I have both been traveling for the past week.

The maintenance cost we are referring to is that neither of us use or are familiar with Bazel, and so if this ever breaks or needs to be updated we'd have no idea what to do to fix it. We also rather not add a bunch of configuration files to this repo to support a variety of build tools, which is why we've stopped supporting cocoapods and Carthage.

Does Bazel have the ability to keep this configuration code in another repo and then point to this repo?

**Comment by tinder-maxwellelliott** [comment]
> @tinder-maxwellelliott Sorry for the delayed response but Stephen and I have both been traveling for the past week.
> 
> The maintenance cost we are referring to is that neither of us use or are familiar with Bazel, and so if this ever breaks or needs to be updated we'd have no idea what to do to fix it. We also rather not add a bunch of configuration files to this repo to support a variety of build tools, which is why we've stopped supporting cocoapods and Carthage.
> 
> Does Bazel have the ability to keep this configuration code in another repo and then point to this repo?

Yes, it is trivial to store this in my repo. I guess I made this PR since it seemed like this project was open source and others could reuse the definitions to build the library.

**Comment by mbrandonw** [comment]
We will happily link to your repo in our readme so that users of Bazel will know how they can use this library in their build system.

**Pull request closed without merging**
